/* BTModule.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-22
 * Author: zhangqiyin/Konishi
 * Email : zhangqiyin@hangsheng.com.cn
 */
#ifndef BTMODULE_H__
#define BTMODULE_H__
#include <string>

#include "rpc_core.h"

using namespace std;

#define BTMODULENAME  "BTModule"

class BTModule
{
public:
    BTModule();
    ~BTModule();

public:
    void setRPC(RPCCore *rpc);
    static void btPlay(void *arg);
    static void btStop(void *arg);
    static void btPrev(void *arg);
    static void btNext(void *arg);

private:
    string m_name;
    static RPCCore *m_rpc;
};

#endif // BTMODULE_H__

