/* MediaModule.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-22
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#ifndef MEDIAMODULE_H__
#define MEDIAMODULE_H__

#define MEDIAMODULENAME  "MediaModule"

enum MediaControlEnum{
    stopMedia = 0,
    playMedia = 1,
    pauseMedia = 2,
    prevMedia = 3,
    nextMedia = 4,
    speedMedia = 5,
    backMedia = 6,
    seekMedia = 7
};

typedef struct {
    MediaControlEnum control_way;
    unsigned int control_para; // speed/back second, or seek to where
}MediaControlStr;

inline void SerialMediaControlStr(void *data, MediaControlStr *mc)
{
    unsigned char *ptr = (unsigned char *)data;
    ptr[0] = (unsigned char)(mc->control_way);
    ptr[1] = (unsigned char)(mc->control_para>>24 & 0xFF);
    ptr[2] = (unsigned char)(mc->control_para>>16 & 0xFF);
    ptr[3] = (unsigned char)(mc->control_para>>8  & 0xFF);
    ptr[4] = (unsigned char)(mc->control_para     & 0xFF);
}

inline void DeserialMediaControlStr(void *data, MediaControlStr *mc)
{
    unsigned char *ptr = (unsigned char *)data;
    mc->control_way = MediaControlEnum(ptr[0]);
    mc->control_para = (ptr[1]<<24 | ptr[2]<<16 | ptr[3]<<8 | ptr[4]);
}

#endif
