/* MediaModuleInterface.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-22
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#ifndef MEDIAMODULE_INTERFACE_H__
#define MEDIAMODULE_INTERFACE_H__

#include "rpc.h"
#include "MediaModule.h"

using namespace std;

Interface MediaModule
{    
public:
    MediaModule();
    ~MediaModule();

public:
    void setRPC(ERPC *rpc);

public:
    static int mediaControl(MediaControlEnum ctl, unsigned int time);

private:
    string m_name;
    static ERPC *m_rpc;
};


#endif // MEDIAMODULE_INTERFACE_H__

