/* MediaModuleInterface.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-22
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#ifndef MEDIAMODULE_INTERFACE_H__
#define MEDIAMODULE_INTERFACE_H__

#include "rpc.h"
#include "MediaModule.h"

using namespace std;

typedef void (*MediaStateChanged)(void *data, size_t len);

Interface MediaModule
{    
public:
    MediaModule();
    ~MediaModule();

public:
    void setRPC(ERPC *rpc);

public:
    static int registerStateHandler(MediaStateChanged handler);
    static int mediaControl(MediaControlEnum ctl, unsigned int time);

private:
    static void mediaStateChanged(void *msg, void *data, size_t len);
    
private:
    string m_name;
    static ERPC *m_rpc;
    static MediaStateChanged m_observer_handler;
};


#endif // MEDIAMODULE_INTERFACE_H__

