/* MediaModuleInterface.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-22
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#include <stdio.h>
#include "MediaModuleInterface.h"

ERPC *MediaModule::m_rpc = NULL;

MediaModule::MediaModule()
{
    m_name.clear();
    m_name = string(MEDIAMODULENAME);
}

MediaModule::~MediaModule()
{
    m_name.clear();
}

void MediaModule::setRPC(ERPC *rpc)
{
    m_rpc = rpc;
}

int MediaModule::mediaControl(MediaControlEnum ctl, unsigned int time)
{
    int result = -1;
    MediaControlStr mc;
    size_t recv_len = 6;
    unsigned char send[6];
    unsigned char recv[6];

    mc.control_way = ctl;
    mc.control_para = time;
    SerialMediaControlStr((void *)send, &mc);
    result = m_rpc->proxyCall("MediaModule", string("mediaControl"), (void *)send, 5, (void *)recv, &recv_len);
    if(result == 0)
    {
        printf("Control media ok:%d\n", (int)recv[0]);
    }
    
    return result;
}

