/* MediaModule.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-22
 * Author: zhangqiyin/Konishi
 * Email : zhangqiyin@hangsheng.com.cn
 */
#ifndef MEDIAMODULE_H__
#define MEDIAMODULE_H__
#include <string>

#include "rpc.h"

using namespace std;

#define MEDIAMODULENAME  "MediaModule"

class MediaModule
{
public:
    MediaModule();
    ~MediaModule();

public:
    void setRPC(HSAERPC *rpc);
    static void mediaPlay(void *arg);
    static void mediaStop(void *arg);
    static void mediaPrev(void *arg);
    static void mediaNext(void *arg);

private:
    string m_name;
    static HSAERPC *m_rpc;
};

#endif // MEDIAMODULE_H__

