/* MediaModule.cpp
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-22
 * Author: zhangqiyin/Konishi
 * Email : zhangqiyin@hangsheng.com.cn
 */
#include <stdio.h>
#include <string.h>
#include "bodydata.h"
#include "MediaModule.h"

RPCCore *MediaModule::m_rpc = NULL;

MediaModule::MediaModule()
{
    m_name.clear();
    m_name = string(MEDIAMODULENAME);
}

MediaModule::~MediaModule()
{
    m_name.clear();
}

void MediaModule::setRPC(RPCCore *rpc)
{
    m_rpc = rpc;
}
static unsigned int count = 0;

void MediaModule::mediaPlay(void *arg)
{
    char *response = (char *)"Media is playing.";
    
    printf("Media start play, count = %u.\n", count);
    
    m_rpc->setResponse(arg, response, strlen(response));
}

void MediaModule::mediaStop(void *arg)
{
    char *response = (char *)"Media is stoping.";
    
    //printf("Media stop play.\n");
    count++;
    m_rpc->setResponse(arg, response, strlen(response));
}

void MediaModule::mediaPrev(void *arg)
{
    char *response = (char *)"Switch previous OK.";
    
    printf("Switch previous media.\n");

    m_rpc->setResponse(arg, response, strlen(response));
}

void MediaModule::mediaNext(void *arg)
{
    char *response = (char *)"Switch next OK.";
    
    printf("Switch next media.\n");

    m_rpc->setResponse(arg, response, strlen(response));
}

