/* socketclient.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-09
 * Author: zhangqiyin/Konishi
 * Email : zhangqiyin@hangsheng.com.cn
 */

#ifndef SOCKET_CLIENT_H__
#define SOCKET_CLIENT_H__
#include <stdio.h>
     
#include "event2/util.h"
#include "event2/event.h"
#include "event2/buffer.h"
#include "event2/thread.h"
#include "event2/listener.h"
#include "event2/bufferevent.h"
     
#include "socketbase.h"

enum SocketMethod{NOSOCKET,TCPSOCKET, LOCALSOCKET};

class SocketClient : public SocketBaseOpt
{
public:
    SocketClient();
    ~SocketClient();

public:
    int connectServer(const char *server);
    int connectServer(const char *server, unsigned int port);
    void disconnectServer(const char *server);
    int sendData(const char *server, const void *data, size_t size);
    
private:  // function
    int createThread(void);
    void destroyThread(void);
    int initEventBase(void);
    void deinitEventBase(void);
    int startConnect(struct sockaddr *s_addr, size_t s_len);
    
private:  // static function
    static void *clientEventThread(void *arg);
    static void readCallback(struct bufferevent *bev, void *user_data);
    static void writeCallback(struct bufferevent *bev, void *user_data);
    static void eventCallback(struct bufferevent *bev, short events, void *user_data);

private:  // variable
    pthread_t client_thread_id;
    struct event_base *client_base;
    
private:  // static variable
    static volatile SocketMethod socket_method;
};
#endif // SOCKET_CLIENT_H__

