/* socketbase.cpp
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-09
 * Author: zhangqiyin/Konishi
 * Email : zhangqiyin@hangsheng.com.cn
 */
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <string.h>

#include <sys/un.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>

#include "socketbase.h"

int SocketBaseOpt::initSockaddr(struct sockaddr_un &s_addr, const char *path)
{
    if(path == NULL)
    {
        printf("SocketBase : path name can not be NULL.\n");
        return -1;
    }

    unlink(path);
    bzero(&s_addr, sizeof(struct sockaddr_un));
    s_addr.sun_family = AF_UNIX;
    strcpy(s_addr.sun_path,path);
    
    return 0;
}

int SocketBaseOpt::initSockaddr(struct sockaddr_in &s_addr, const char *ip, unsigned int port)
{
    int result = -1;

    if(ip == NULL)
    {
        printf("SocketBase : ip addr can not be NULL.\n");
        return -1;
    }

    bzero(&s_addr,sizeof(struct sockaddr_in));
    s_addr.sin_family = AF_INET;
    s_addr.sin_port   = htons(port);
    if(strncasecmp(ip,"INADDR_ANY",10) == 0)
    {
        printf("SocketBase : using INADDR_ANY:%d as ip addr.\n",port);
        s_addr.sin_addr.s_addr = INADDR_ANY;
    }
    else
    {
        printf("SocketBase : using %s:%d as ip addr.\n",ip,port);
        result = inet_aton(ip,(struct in_addr *)&s_addr.sin_addr.s_addr);
        if(result == 0)
        {
            printf("SocketBase : add ip addr failed: %s\n",strerror(errno));
            return -1;
        }
    }

    return 0;
}


