/* bodydata.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-22
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#ifndef BODYDATA_H__
#define BODYDATA_H__
#include <string>
#include "message.h"

using namespace std;

#define SENDERTAG       0x534E  // SN
#define RECVERTAG       0x524E  // RN
#define MODULETAG       0x4D4E  // MN
#define FUNCTIONTAG     0x464E  // FN
#define BODYDATATAG     0x4244  // BD

class BodyData{
public:
    BodyData();
    ~BodyData();

public:
    size_t size(void);
    void clear(void);
    void setSender(const string &sender);
    string getSender(void);
    void setRecver(const string &recver);
    string getRecver(void);
    void setModule(const string &module);
    string getModule(void);
    void setFunction(const string &func);
    string getFunction(void);
    int mallocBodyData(void **data, const void *send, unsigned int len);
    int mallocRecvBodyData(void **data, const unsigned char *recv, unsigned int len);
    void releaseBodyData(void *data);
    void *getUserBodyData(void *arg, unsigned int *len);
    
private:
    size_t length;
    string sender;
    string recver;
    string module;
    string function;
    void *realdata;
    unsigned int reallen;
    MessageStr *message;
};

#endif // BODYDATA_H__

