/* bodydata.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-22
 * Author: zhangqiyin/Konishi
 * Email : zhangqiyin@hangsheng.com.cn
 */
#ifndef BODYDATA_H__
#define BODYDATA_H__
#include <string>
using namespace std;

#define SENDERTAG       0x534E  // SN
#define RECVERTAG       0x524E  // RN
#define MODULETAG       0x4D4E  // MN
#define FUNCTIONTAG     0x464E  // FN
#define BODYDATATAG     0x4244  // BD

class BodyData{
public:
    BodyData();
    ~BodyData();

public:
    size_t size(void);
    void setSender(const string &sender);
    string getSender(void);
    void setRecver(const string &recver);
    string getRecver(void);
    void setModule(const string &module);
    string getModule(void);
    void setFunction(const string &func);
    string getFunction(void);
    int setApplyBodyData(void **data, void *send, unsigned int len);
    void getApplyBodyData(void *data, void **recv, unsigned int *len);
    
private:
    size_t length;
    string sender;
    string recver;
    string module;
    string function;
    
};

#endif // BODYDATA_H__

