/* bodydata.cpp
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-22
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "bodydata.h"

#define BD_DEBUG   printf
#define BD_INFO    printf
#define BD_WARN    printf
#define BD_ERROR   printf

BodyData::BodyData()
{
    length = 0;
    message = NULL;
    sender.clear();
    recver.clear();
    module.clear();
    realdata = NULL;
    function.clear();
}

BodyData::~BodyData()
{
    length = 0;
    message = NULL;
    sender.clear();
    recver.clear();
    module.clear();
    realdata = NULL;
    function.clear();
}

size_t BodyData::size(void)
{
    return this->length;
}

void BodyData::clear(void)
{
    length = 0;
    message = NULL;
    sender.clear();
    recver.clear();
    module.clear();
    function.clear();
}

void BodyData::setSender(const string &sender)
{
    this->sender = sender;
}

string BodyData::getSender(void)
{
    return this->sender;
}

void BodyData::setRecver(const string &recver)
{
    this->recver = recver;
}

string BodyData::getRecver(void)
{
    return this->recver;
}

void BodyData::setModule(const string &module)
{
    this->module = module;
}

string BodyData::getModule(void)
{
    return this->module;
}

void BodyData::setFunction(const string &func)
{
    this->function = func;
}

string BodyData::getFunction(void)
{
    return this->function;
}

int BodyData::mallocBodyData(void **data, const void *send, unsigned int len)
{
    unsigned int i = 0;
    unsigned int size = 0;
    unsigned char *ptr = NULL;

    if(this->sender.size())
        size += sender.size() + 2 + 1;
    if(this->recver.size())
        size += recver.size() + 2 + 1;
    if(this->module.size())
        size += module.size() + 2 + 1;
    if(this->function.size())
        size += function.size() + 2 + 1;

    size += len + 2 + 4; // two magic and four length
    this->length = size;
    *data = (void *)malloc(size);
    if(*data == NULL)
    {
        BD_ERROR("BodyData : malloc body data failed!\n");
        return -1;
    }
    
    ptr = (unsigned char *)*data;

    if(this->sender.size())
    {
        ptr[0] = (SENDERTAG>>8) & 0xFF;
        ptr[1] = SENDERTAG & 0xFF;
        ptr[2] = sender.size();
        memcpy(&ptr[3], sender.c_str(), sender.size());
        i += 3 + sender.size();
    }
    if(this->recver.size())
    {
        ptr[i] = (RECVERTAG>>8) & 0xFF;
        ptr[i+1] = RECVERTAG & 0xFF;
        ptr[i+2] = recver.size();
        memcpy(&ptr[i+3], recver.c_str(), recver.size());
        i += 3 + recver.size();
    }
    if(this->module.size())
    {
        ptr[i] = (MODULETAG>>8) & 0xFF;
        ptr[i+1] = MODULETAG & 0xFF;
        ptr[i+2] = module.size();
        memcpy(&ptr[i+3], module.c_str(), module.size());
        i += 3 + module.size();
    }
    if(this->function.size())
    {
        ptr[i] = (FUNCTIONTAG>>8) & 0xFF;
        ptr[i+1] = FUNCTIONTAG & 0xFF;
        ptr[i+2] = function.size();
        memcpy(&ptr[i+3], function.c_str(), function.size());
        i += 3 + function.size();
    }
    ptr[i] = (BODYDATATAG>>8) & 0xFF;
    ptr[i+1] = BODYDATATAG & 0xFF;
    ptr[i+2] = (len>>24) & 0xFF;
    ptr[i+3] = (len>>16) & 0xFF;
    ptr[i+4] = (len>>8) & 0xFF;
    ptr[i+5] = len & 0xFF;
    if(len != 0)
        memcpy(&ptr[i+6], send, len);
    
    return 0;
}

int BodyData::mallocRecvBodyData(void **data, const unsigned char *recv, unsigned int len)
{
    unsigned char *ptr = NULL;

    *data = (void *)malloc(len);
    if(*data == NULL)
    {
        BD_ERROR("BodyData : malloc body data failed!\n");
        return -1;
    }
    ptr = (unsigned char *)*data;
    memcpy(ptr, recv, len);
    
    return 0;
}

void BodyData::releaseBodyData(void *data)
{
    if(data)
        free(data);
}

void *BodyData::getUserBodyData(void *arg, unsigned int *len)
{
    bool loop = true;
    unsigned char *ptr = NULL;
    this->message = (MessageStr *)arg;
    
    if(message == NULL)
        return NULL;
    
    ptr = (unsigned char *)message->body_data;
    while(loop)
    {
        switch(ptr[0])
        {
            case (SENDERTAG>>8) & 0xFF:
                this->sender.append((const char *)&ptr[3],ptr[2]);
                ptr += ptr[2] + 3;
                break;
                
            case (RECVERTAG>>8) & 0xFF:
                this->recver.append((const char *)&ptr[3],ptr[2]);
                ptr += ptr[2] + 3;
                break;
                
            case (MODULETAG>>8) & 0xFF:
                this->module.append((const char *)&ptr[3],ptr[2]);
                ptr += ptr[2] + 3;
                break;
                
            case (FUNCTIONTAG>>8) & 0xFF:
                this->function.append((const char *)&ptr[3],ptr[2]);
                ptr += ptr[2] + 3;
                break;
                
            case (BODYDATATAG>>8) & 0xFF:
                reallen = ptr[2]<<24 | ptr[3]<<16 | ptr[4]<<8 | ptr[5];
                realdata = (void *)&ptr[6];
                if(len)
                    *len = reallen;
                loop = false;
                break;
            default:
                break;
        }
    }

    return realdata;
}

