/* socketbase.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-09
 * Author: Konishi
 * Email : konishi5202@163.com
 */

#ifndef SOCKET_BASE_H__
#define SOCKET_BASE_H__

#ifdef __cplusplus
extern "C" {
#endif

#define EXTERN  extern
#define STATIC  static

EXTERN int initLSocketAddr(struct sockaddr_un &s_addr, const char *path);
EXTERN int initNSocketAddr(struct sockaddr_in &s_addr, const char *ip, unsigned int port);

#ifdef __cplusplus
}
#endif

#endif  // SOCKET_BASE_H__

