/* nil_pointer_list.cpp
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-09
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#include <stdio.h>

using namespace std;

#include "nil_pointer_list.h"

#define K_DEBUG   printf
#define K_INFO    printf
#define K_WARN    printf
#define K_ERROR   printf

NILPointerList::NILPointerList()
{
    nilp_list.clear();
}

NILPointerList::~NILPointerList()
{
    nilp_list.clear();
}

int NILPointerList::size(void)
{
    return nilp_list.size();
}

void NILPointerList::clear(void)
{
    nilp_list.clear();
}

bool NILPointerList::empty(void)
{
    return nilp_list.empty();
}

void *NILPointerList::find(void *addr)
{
    for(it = nilp_list.begin(); it != nilp_list.end(); it++)
    {
        if(addr == *it)
            return *it;
    }

    return NULL;
}

int NILPointerList::insert(void *addr)
{
    nilp_list.push_back(addr);
//    nilp_list.push_front(addr);
//    nilp_list.insert(nilp_list.begin(), addr);
//    nilp_list.insert(nilp_list.end(), addr);
    return 0;
}

int NILPointerList::remove(void *addr)
{
    nilp_list.remove(addr);
    return 0;
}

