/* pointer_list.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-14
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#ifndef POINTER_LIST_H__
#define POINTER_LIST_H__
#include <list>

class PointerList
{
public:
    PointerList();
    ~PointerList();

public:
    int size(void);
    void clear(void);
    bool empty(void);
    void *begin(void);
    void *next(void);
    bool hasNext(void);
    void *find(void *addr);
    int insert(void *addr);
    int remove(void *addr);

private:
    list<void *> m_list;
    list<void *>::iterator it;
};

#endif // POINTER_LIST_H__

