/* module_config.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-28
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#ifndef MODULE_CONFIG_H__
#define MODULE_CONFIG_H__
#include <string>

using namespace std;

class ModuleConfig
{
public:
    ModuleConfig();
    ~ModuleConfig();

public:
    int setConfigProfile(const string &path);
    int getFixThreadNum(void);
    int getDynThreadNum(void);
    int getMaxQueueNum(void);
    int referModule(const string &module, string &process);
    
public: // for test and debug
    void printSection(void);
    void printConfiguration(void);

private:
    bool path_init;
};

#endif  //NETWORK_CONFIG_H__

