/* module_config.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-28
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#ifndef MODULE_CONFIG_H__
#define MODULE_CONFIG_H__
#include <string>
#include "inifile.h"
using namespace inifile;

#define MODULEBUILDSECTION "ModuleBuild"

class ModuleConfig
{
public:
    ModuleConfig();
    ~ModuleConfig();

public:
    int setConfigProfile(const string &path);
    int referModule(const string &module, string &process);
    
public: // for test and debug, if use change to public
    void printSection(void);
    void printConfiguration(void);

private:
    bool path_init;
    IniFile m_inifile;
};

#endif  //NETWORK_CONFIG_H__

