/* network_config.cpp
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-28
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>

#include "network_config.h"

#define NM_DEBUG   printf
#define NM_INFO    printf
#define NM_WARN    printf
#define NM_ERROR   printf

NetworkConfig::NetworkConfig()
{
    path_init = false;
}

NetworkConfig::~NetworkConfig()
{
    path_init = false;
}

int NetworkConfig::setConfigProfile(const string &path)
{
    int ret = -1;
    
    if(path.empty())
    {
        NM_ERROR("NetworkConfig : config-file path can not be NULL!\n");
        return -1;
    }
    
    ret = m_inifile.load(path);
    if(ret != 0)
    {
        path_init = false;
        NM_ERROR("NetworkConfig : load %s config-file failed!\n", path.c_str());
        return -1;
    }
    
    path_init = true;

    if(!m_inifile.hasKey(GLOBALSECTION, string(COMMTIMEOUTKEY)))
    {
        NM_ERROR("NetworkConfig : does't not have %s:%s config, please check!\n", GLOBALSECTION, COMMTIMEOUTKEY);
        return -1;
    }

    if(!m_inifile.hasKey(GLOBALSECTION, string(CONNECTTIMEOUTKEY)))
    {
        NM_ERROR("NetworkConfig : does't not have %s:%s config, please check!\n", GLOBALSECTION, CONNECTTIMEOUTKEY);
        return -1;
    }
    
    return ret;
}

int NetworkConfig::getNetworkConfig(const string &section, SocketStruct &addr)
{
    int ret = -1;
    
    if(!m_inifile.hasSection(section))
    {
        NM_ERROR("NetworkConfig : does't not have %s process config, please check!\n", section.c_str());
        return -1;
    }

    if(!m_inifile.hasKey(section, string(IPKEY)))
    {
        NM_ERROR("NetworkConfig : does't not have %s:%s config, please check!\n", section.c_str(), IPKEY);
        return -1;
    }

    if(!m_inifile.hasKey(section, string(PORTKEY)))
    {
        NM_ERROR("NetworkConfig : does't not have %s:%s config, please check!\n", section.c_str(), PORTKEY);
        return -1;
    }

    addr.ipaddr = m_inifile.getStringValue(section, string(IPKEY),ret);
    addr.port = m_inifile.getIntValue(section, string(PORTKEY),ret);
    
    return 0;
}

void NetworkConfig::printSection(void)
{
    IniFile::iterator it;

    NM_INFO("NetworkConfig : Section:\n");
    for(it = m_inifile.begin();it != m_inifile.end(); ++it)
        NM_INFO(" %s\n",it->first.c_str());
    NM_INFO("\n");
}

void NetworkConfig::printConfiguration(void)
{
    IniFile::iterator it;
    IniSection::iterator iti;
    
    NM_INFO("NetworkConfig : Configurations:\n");
    for(it = m_inifile.begin();it != m_inifile.end(); ++it)
    {
        NM_INFO(" %s\n",it->first.c_str());
        for(iti = it->second->items.begin();iti != it->second->items.end(); ++iti)
        {
            NM_INFO("  %s=%s\n", iti->key.c_str(), iti->value.c_str());
        }
    }
    NM_INFO("\n");
}

