/* network_config.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-28
 * Author: Konishi
 * Email : konishi5202@163.com
 */

#ifndef NETWORK_CONFIG_H__
#define NETWORK_CONFIG_H__
#include <string>

typedef struct {
    string ipaddr;
    unsigned int port;
}SocketStruct;

class NetworkConfig
{
public:
    NetworkConfig();
    ~NetworkConfig();

public:
    int setConfigProfile(const string &path);
    void getConnectTimeout(struct timeval *tv);
    void getCommunicateTimeout(struct timeval *tv);
    int getNetworkConfig(const string &section, SocketStruct &addr);
    
public: // for test and debug
    void printSection(void);
    void printConfiguration(void);

private:
    bool path_init;
};


#endif  //NETWORK_CONFIG_H__

