/* network_config.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-28
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#ifndef NETWORK_CONFIG_H__
#define NETWORK_CONFIG_H__
#include <string>
#include "inifile.h"
using namespace inifile;

#define GLOBALSECTION       "Global"
#define COMMTIMEOUTKEY      "CommunicateTimeout"
#define CONNECTTIMEOUTKEY   "ConnectTimeout"

#define IPKEY   "IPAddress"
#define PORTKEY "MonitorPort"

typedef struct {
    string ipaddr;
    unsigned int port;
}SocketStruct;

class NetworkConfig
{
public:
    NetworkConfig();
    ~NetworkConfig();

public:
    int setConfigProfile(const string &path);
    int getNetworkConfig(const string &section, SocketStruct &addr);
    
public: // for test and debug, if use change to public
    void printSection(void);
    void printConfiguration(void);

private:
    bool path_init;
    IniFile m_inifile;
};

#endif  //NETWORK_CONFIG_H__

