/* message.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-23
 * Author: zhangqiyin/Konishi
 * Email : zh5202@163.com
 */
#ifndef MESSAGE_H__
#define MESSAGE_H__
#include <time.h>

#define MESSAGE_MAGIC_NUM   0xF55F

#define MESSAGE_MAJOR_VERSION   0
#define MESSAGE_MINOR_VERSION   1

#define MESSAGE_HEAD_SIZE       32

#define getUnsignedIntData(ptr)     ((ptr)[0]<<24 | (ptr)[1]<<16 | (ptr)[2]<<8 | (ptr)[3])
#define getUnsignedShortData(ptr)   ((ptr)[0]<<8 | (ptr)[1])
#define getMESSAGETYPE(ch)          ((MESSAGE_TYPE)(((ch)>>4) & 0xF))
#define getSERIALIZETYPE(ch)        ((SERIALIZE_TYPE)((ch) & 0xF))
#define getONEWAYSTATUS(ch)         ((ch) & 0x80)
#define getRESPONSESTATUS(ch)       ((ch) & 0x40)

enum MESSAGE_TYPE{
    MT_MIN_PK   = 0,
    MT_LINK_PK  = 1,
    MT_BEAT_PK  = 2,
    MT_APPLY_PK = 3,
    MT_MAX_PK   = 4
};

enum SERIALIZE_TYPE{
    ST_MIN_BD   = 0,
    ST_XML_BD   = 1,
    ST_BIN_BD   = 2,
    ST_JSON_BD  = 3,
    ST_USER_BD  = 4,
    ST_MAX_BD   = 5
};

typedef struct{
    unsigned int magic:16;
    unsigned int head_size:16;
    unsigned char version;
    MESSAGE_TYPE message_type:4;
    SERIALIZE_TYPE serialize_type:4;
    bool one_way:1;   // 0, need back, 1, not need
    bool response:1;  // 0, request, 1, reponse
    struct timespec timesp;
    unsigned int status_code:16;
    unsigned int message_id;
    //    unsigned char Reserved[12];
    unsigned int body_size;
    void *body_data;
}MessageStr;

extern void initMessage(MessageStr &msg);
extern void setMessageType(MessageStr &msg, MESSAGE_TYPE type);
extern void setSerializeType(MessageStr &msg, SERIALIZE_TYPE type);
extern void setOnewayFlag(MessageStr &msg, bool flag);
extern void setResponseFlag(MessageStr &msg, bool flag);
extern void setTimeout(MessageStr &msg, struct timespec &tv);
extern void setStatusCode(MessageStr &msg, unsigned int code);
extern void setMessageID(MessageStr &msg, unsigned int id);
extern void setBodyData(MessageStr &msg, void *data, unsigned int size);

extern int getHeadFromData(MessageStr &head, const void *data);
extern int getDataFromHead(const void *data, MessageStr &head);

#endif

