/* message.cpp
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-23
 * Author: zhangqiyin/Konishi
 * Email : zh5202@163.com
 */
#include <stdio.h>
#include <stdlib.h>
#include "message.h"

#define MSG_DEBUG   printf
#define MSG_INFO    printf
#define MSG_WARN    printf
#define MSG_ERROR   printf

static int checkMessageType(MESSAGE_TYPE mt)
{
    if((mt <= MT_MIN_PK) || (mt >=MT_MAX_PK))
        return -1;
    
    return 0;
}

static int checkSerializeType(SERIALIZE_TYPE st)
{
    if((st <= ST_MIN_BD) || (st >= ST_MAX_BD))
        return -1;
    return 0;
}

int getHeadFromData(MessageStr &head, const char *data)
{
    unsigned char *ptr = (unsigned char *)data;
    
    head.magic = getUnsignedIntData(ptr);
    head.version = getUnsignedSIntData(ptr + 4);
    head.head_size = getUnsignedSIntData(ptr + 6);
    
    head.message_type = getMESSAGETYPE(ptr[8]);
    head.serialize_type = getSERIALIZETYPE(ptr[8]);
    
    if(getONEWAYSTATUS(ptr[9]))
        head.one_way = true;
    else
        head.one_way = false;
    if(getRESPONSESTATUS(ptr[9]))
        head.response = true;
    else
        head.response = false;
    
    head.timeout.tv_sec = (ptr[9]&0x3F)<<8 | ptr[10]>>2;
    head.timeout.tv_usec = (ptr[10]&0x3)<<8 | ptr[11];
    
    head.status_code = getUnsignedIntData(ptr + 12);
//    memcpy(head.Reserved, &ptr[16], 8);
    head.message_id = getUnsignedIntData(ptr + 24);
    head.body_size = getUnsignedIntData(ptr + 28);
    
    if(MESSAGE_MAGIC_NUM != head.magic)
    {
        MSG_ERROR("Message : magic does't match!\n");
        return -1;
    }

    if((MESSAGE_MAJOR_VERSION != ((head.version >> 8) & 0xFF)) ||
       (MESSAGE_MINOR_VERSION != (head.version & 0xFF)))
    {
        MSG_ERROR("Message : version does't match!\n");
        return -1;
    }

    if(MESSAGE_HEAD_SIZE != head.head_size)
    {
        MSG_ERROR("Message : version does't match!\n");
        return -1;
    }

    if(checkMessageType(head.message_type))
    {
        MSG_ERROR("Message : message type does't fit the bill!\n");
        return -1;
    }

    if(checkSerializeType(head.serialize_type))
    {
        MSG_ERROR("Message : serialize type does't fit the bill!\n");
        return -1;
    }
    
    return  0;
}

