/* message.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-23
 * Author: zhangqiyin/Konishi
 * Email : zh5202@163.com
 */
#ifndef MESSAGE_H__
#define MESSAGE_H__
#include <sys/time.h>

#define MESSAGE_MAGIC_NUM   0xF050F050

#define MESSAGE_MAJOR_VERSION   0
#define MESSAGE_MINOR_VERSION   1

#define MESSAGE_HEAD_SIZE       32

#define getUnsignedIntData(ptr)     ((ptr)[0]<<24 | (ptr)[1]<<16 | (ptr)[2]<<8 | (ptr)[3])
#define getUnsignedSIntData(ptr)    ((ptr)[0]<<8 | (ptr)[1])
#define getMESSAGETYPE(ch)          ((MESSAGE_TYPE)(((ch)>>4) & 0xF))
#define getSERIALIZETYPE(ch)        ((SERIALIZE_TYPE)((ch) & 0xF))
#define getONEWAYSTATUS(ch)         ((ch) & 0x80)
#define getRESPONSESTATUS(ch)       ((ch) & 0x40)

enum MESSAGE_TYPE{
    MT_MIN_PK   = 0,
    MT_LINK_PK  = 1,
    MT_BEAT_PK  = 2,
    MT_APPLY_PK = 3,
    MT_MAX_PK   = 4
};

enum SERIALIZE_TYPE{
    ST_MIN_BD   = 0,
    ST_XML_BD   = 1,
    ST_BIN_BD   = 2,
    ST_JSON_BD  = 3,
    ST_USER_BD  = 4,
    ST_MAX_BD   = 5
};

typedef struct{
    unsigned int magic;
    unsigned int version;
    unsigned int head_size;
    MESSAGE_TYPE message_type;
    SERIALIZE_TYPE serialize_type;
    bool one_way;   // 0, need back, 1, not need
    bool response;  // 0, request, 1, reponse
    struct timeval timeout;
    unsigned int status_code;
//    unsigned char Reserved[8];
    unsigned int message_id;
    unsigned int body_size;
    char *body_data;
}MessageStr;

#endif

