/* int_hash.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-14
 * Author: Konishi
 * Email : konishi5202@163.com
 */

#ifndef INT_HASH_H__
#define INT_HASH_H__
#include <map>
#include <string>

using namespace std;
typedef map<unsigned int, void *>INT_MAP;

class INTHash
{
public:
    INTHash();
    ~INTHash();

public:
    void print(void);
    int size(void);
    void clear(void);
    bool empty(void);
    void *find(unsigned int &key);
    int remove(unsigned int &key);
    int insert(unsigned int &key, void *value);
    int change(unsigned int &key, void *value);

private:
    INT_MAP int_map;
    INT_MAP::iterator it;
};

#endif // RPC_HASH_H__

