/* proxy.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-20
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#ifndef PROXY_H__
#define PROXY_H__
#include <pthread.h>

class Proxy
{
public:
    Proxy();
    ~Proxy();

    int init(void);
    void destroy(void);    
    int wait(struct timeval &tv);
    void wakeup(void);

    void setRequestMsg(void *msg);
    void *getRequestMsg(void);
    void setResponseMsg(void *msg);
    void *getResponseMsg(void);
    
private:
    void *request;
    void *response;
};

#endif // PROXY_H__