/* rpc.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-22
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#include "rpc.h"
#include "rpc_core.h"

ERPC *ERPC::m_erpc = NULL;;

ERPC::ERPC()
{
    m_erpc = NULL;
}

ERPC::~ERPC()
{
    if(m_erpc)
        delete (m_erpc);
    m_erpc = NULL;
}

ERPC *ERPC::getInstance(void)
{
    if(m_erpc)
        return m_erpc;

    m_erpc = RPCCore::getInstance();
    return m_erpc;
}

