/* rpc_list.cpp
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-09
 * Author: zhangqiyin/Konishi
 * Email : zhangqiyin@hangsheng.com.cn
 */
#include <stdio.h>
     
#include "rpc_list.h"

RPCList::RPCList()
{
    rpc_list.clear();
}

RPCList::~RPCList()
{
    rpc_list.clear();
}

int RPCList::size(void)
{
    return rpc_list.size();
}

void RPCList::clear(void)
{
    rpc_list.clear();
}

bool RPCList::empty(void)
{
    return rpc_list.empty();
}

void *RPCList::find(void *addr)
{
    for(it = rpc_list.begin(); it != rpc_list.end(); it++)
    {
        if(addr == *it)
            return *it;
    }

    return NULL;
}

int RPCList::insert(void *addr)
{
    rpc_list.push_back(addr);
//    rpc_list.push_front(addr);
//    rpc_list.insert(rpc_list.begin(), addr);
//    rpc_list.insert(rpc_list.end(), addr);
    return 0;
}

int RPCList::remove(void *addr)
{
    rpc_list.remove(addr);
    return 0;
}

