/* rpc_list.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-14
 * Author: Konishi
 * Email : konishi5202@163.com
 */
#ifndef RPC_LIST_H__
#define RPC_LIST_H__
#include <list>
#include <string>
     
using namespace std;

class RPCList
{
public:
    RPCList();
    ~RPCList();

    int size(void);
    void clear(void);
    bool empty(void);
    void *find(void *addr);
    int insert(void *addr);
    int remove(void *addr);

private:
    list<void *> rpc_list;
    list<void *>::iterator it;
};

#endif // RPC_LIST_H__

