/* rpc_hash.h
 * DO NOT EDIT THIS FILE.
 * Date  : 2017-11-14
 * Author: Konishi
 * Email : konishi5202@163.com
 */

#ifndef RPC_HASH_H__
#define RPC_HASH_H__
#include <map>
#include <string>

using namespace std;
typedef map<string, void *>RPC_MAP;

class RPCHash
{
public:
    RPCHash();
    ~RPCHash();

public:
    void print(void);
    int size(void);
    void clear(void);
    bool empty(void);
    void *find(const string &key);
    int remove(const string &key);
    int insert(const string &key, void *value);
    int change(const string &key, void *value);

private:
    RPC_MAP rpc_map;
    RPC_MAP::iterator it;
};

#endif // RPC_HASH_H__

